export const metadata = {
  title: 'auth',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <h1>Auth Layout</h1>
        {children}
      </body>
    </html>
  )
}
