"use client";

import Link from "next/link";
// import { useRouter } from "next/router";
import { useState } from "react";

// export const metadata = {
//   title: "auth",
//   description: "Generated by Next.js",
// };

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [input, setInput] = useState("");
  // const router = useRouter()
  return (
    <>
      <input value={input} onChange={(e) => setInput(e.target.value)} />
      <Link href={'/login'}>login</Link>
      <Link href={'/signup'}>Singup</Link>
      <div>
        <h1>Auth Layout</h1>
        {children}
      </div>
    </>
  );
}
