import { Metadata } from "next"

export const metadata : Metadata = {
  title: {
    absolute:"", // used to ignore all title and set what is here
    default:"My_next_14", // default title for all rout which is not set
    template:"%s | Ganesh" // used to set all prefix or sufix words
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
