export const metadata = {
  title: 'login',
  description: 'Generated by Next.js',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}
      <h1>login Layout</h1>
      </body>
    </html>
  )
}
