import { Metadata } from 'next'
import Link from 'next/link'
import React from 'react'

export const metadata : Metadata = {
  title: {
    absolute:"Products", // used to ignore all title and set what is here
  },
  description: 'Generated by Next.js',
}

const Product = () => {
  return (
    <h1><Link href={'product/1'} replace>product 1</Link></h1>
  )
}

export default Product