import { Metadata } from 'next'
import React from 'react'

export const metadata : Metadata = {
  title: {
    absolute:"Products", // used to ignore all title and set what is here
  },
  description: 'Generated by Next.js',
}

const Product = () => {
  return (
    <div>Products</div>
  )
}

export default Product